# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'WeatherWayApp' do
#  pod 'NVActivityIndicatorView'
  pod 'Alamofire', '~> 3.0'
  pod 'Polyline', '~> 2.0'
  pod 'NVActivityIndicatorView'

end

target 'WeatherWayAppTests' do

end

target 'WeatherWayAppUITests' do

end

target 'WeatherWatch' do

end

target 'WeatherWatch Extension' do

end

